### ISSUE TITLE
Default access token and core id for demo on Thursday

### ISSUE THREAD

**Issue by rahilj** [krazineurons/sparky#8]
to
83b34c45ed81f97f8dbb1b857d116868bfc22e35
53ff70066667574820402067

Will save time when doing multiple runs

**Comment by krazineurons** [comment]
The access token looks bigger than before,  is it correct one? For which
deviceid u need it?you can always append it in the url,  you want it for
the test remote?

**Comment by rahilj** [comment]
Sorry for confusion Anigo.
 the access token is 83b34c45ed81f97f8dbb1b857d116868bfc22e35 . Device id the 53ff70066667574820402067
Could you share the url format?
Additionally, the demo isn't working currently. There is no code coming in ...

**Comment by rahilj** [comment]
Never mind, it works. There was an issue with my receiver antennae. Thanks.
I still need the url format to append the credentials

**Comment by krazineurons** [comment]
Here you go

http://krazineurons.github.io/sparky/HackAJoe/?deviceid=<>&accesstoken=<>

Replace the <> with your values

**Comment by rahilj** [comment]
works, thanks
tested with phone as well
